# coding: utf-8

"""
    Confidentify API

    Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses.   # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from confidentify_client.configuration import Configuration


class AuthResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'access_token': 'str',
        'registered': 'bool'
    }

    attribute_map = {
        'access_token': 'access_token',
        'registered': 'registered'
    }

    def __init__(self, access_token=None, registered=None, local_vars_configuration=None):  # noqa: E501
        """AuthResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._access_token = None
        self._registered = None
        self.discriminator = None

        if access_token is not None:
            self.access_token = access_token
        if registered is not None:
            self.registered = registered

    @property
    def access_token(self):
        """Gets the access_token of this AuthResponse.  # noqa: E501

        An access token to be provided in requests to the API via the `Authorization` HTTP header. The header value should prefixed with `Bearer` and a single space, so: `Bearer `.   # noqa: E501

        :return: The access_token of this AuthResponse.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this AuthResponse.

        An access token to be provided in requests to the API via the `Authorization` HTTP header. The header value should prefixed with `Bearer` and a single space, so: `Bearer `.   # noqa: E501

        :param access_token: The access_token of this AuthResponse.  # noqa: E501
        :type: str
        """

        self._access_token = access_token

    @property
    def registered(self):
        """Gets the registered of this AuthResponse.  # noqa: E501

        Indicates whether the user has a registered account or not. If authentication was able to validate user credentials but an account has not been registered for this user, the user will be able to call a limited set of endpoints in order to register an account.   # noqa: E501

        :return: The registered of this AuthResponse.  # noqa: E501
        :rtype: bool
        """
        return self._registered

    @registered.setter
    def registered(self, registered):
        """Sets the registered of this AuthResponse.

        Indicates whether the user has a registered account or not. If authentication was able to validate user credentials but an account has not been registered for this user, the user will be able to call a limited set of endpoints in order to register an account.   # noqa: E501

        :param registered: The registered of this AuthResponse.  # noqa: E501
        :type: bool
        """

        self._registered = registered

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AuthResponse):
            return True

        return self.to_dict() != other.to_dict()
