# coding: utf-8

"""
    Confidentify API

    Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses.   # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from confidentify_client.configuration import Configuration


class IngestFileRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_type': 'str',
        'record_source': 'str'
    }

    attribute_map = {
        'file_type': 'file_type',
        'record_source': 'record_source'
    }

    def __init__(self, file_type=None, record_source=None, local_vars_configuration=None):  # noqa: E501
        """IngestFileRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._file_type = None
        self._record_source = None
        self.discriminator = None

        if file_type is not None:
            self.file_type = file_type
        if record_source is not None:
            self.record_source = record_source

    @property
    def file_type(self):
        """Gets the file_type of this IngestFileRequest.  # noqa: E501

        Defines the type of file and thus also the type of data ingestion to perform.   # noqa: E501

        :return: The file_type of this IngestFileRequest.  # noqa: E501
        :rtype: str
        """
        return self._file_type

    @file_type.setter
    def file_type(self, file_type):
        """Sets the file_type of this IngestFileRequest.

        Defines the type of file and thus also the type of data ingestion to perform.   # noqa: E501

        :param file_type: The file_type of this IngestFileRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["records.csv", "documents.zip", "document.pdf", "document.png", "document.jpg"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and file_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `file_type` ({0}), must be one of {1}"  # noqa: E501
                .format(file_type, allowed_values)
            )

        self._file_type = file_type

    @property
    def record_source(self):
        """Gets the record_source of this IngestFileRequest.  # noqa: E501

        Defines a string which identifies the source of any records in the file. This could be the original filename or the name of the originating data source.   # noqa: E501

        :return: The record_source of this IngestFileRequest.  # noqa: E501
        :rtype: str
        """
        return self._record_source

    @record_source.setter
    def record_source(self, record_source):
        """Sets the record_source of this IngestFileRequest.

        Defines a string which identifies the source of any records in the file. This could be the original filename or the name of the originating data source.   # noqa: E501

        :param record_source: The record_source of this IngestFileRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                record_source is not None and len(record_source) > 100):
            raise ValueError("Invalid value for `record_source`, length must be less than or equal to `100`")  # noqa: E501

        self._record_source = record_source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IngestFileRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IngestFileRequest):
            return True

        return self.to_dict() != other.to_dict()
