# coding: utf-8

"""
    Confidentify API

    Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses.   # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from confidentify_client.configuration import Configuration


class MatchJobPairsQueryResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'pairs': 'list[MatchedPair]',
        'next_page': 'NextPageInformation'
    }

    attribute_map = {
        'pairs': 'pairs',
        'next_page': 'next_page'
    }

    def __init__(self, pairs=None, next_page=None, local_vars_configuration=None):  # noqa: E501
        """MatchJobPairsQueryResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._pairs = None
        self._next_page = None
        self.discriminator = None

        if pairs is not None:
            self.pairs = pairs
        if next_page is not None:
            self.next_page = next_page

    @property
    def pairs(self):
        """Gets the pairs of this MatchJobPairsQueryResponse.  # noqa: E501

        The record pairs retrieved from the query.   # noqa: E501

        :return: The pairs of this MatchJobPairsQueryResponse.  # noqa: E501
        :rtype: list[MatchedPair]
        """
        return self._pairs

    @pairs.setter
    def pairs(self, pairs):
        """Sets the pairs of this MatchJobPairsQueryResponse.

        The record pairs retrieved from the query.   # noqa: E501

        :param pairs: The pairs of this MatchJobPairsQueryResponse.  # noqa: E501
        :type: list[MatchedPair]
        """

        self._pairs = pairs

    @property
    def next_page(self):
        """Gets the next_page of this MatchJobPairsQueryResponse.  # noqa: E501


        :return: The next_page of this MatchJobPairsQueryResponse.  # noqa: E501
        :rtype: NextPageInformation
        """
        return self._next_page

    @next_page.setter
    def next_page(self, next_page):
        """Sets the next_page of this MatchJobPairsQueryResponse.


        :param next_page: The next_page of this MatchJobPairsQueryResponse.  # noqa: E501
        :type: NextPageInformation
        """

        self._next_page = next_page

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchJobPairsQueryResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MatchJobPairsQueryResponse):
            return True

        return self.to_dict() != other.to_dict()
