# coding: utf-8

"""
    Confidentify API

    Services that let you build confidence and identify matches in customer data. ## Features overview * Contact data processing services (tagged with `process`) which offer   validation and enrichment backed by inference and knowledge on complex   data types such as names, email addresses, phone numbers.  * Data matching and searching services (tagged with `matching`) that    allow you to identify duplicated data or matches against third party   contact data list.  * Dataset management services (tagged with `dataset`) that allow record storage and retrieval. ## Integrator notes: * Use the `/auth` endpoint to get an access token. Access tokens are temporary, so design the client the be capable of renewing it. * The APIs are rate-limited, so design the client to be capable of retrying with some delay upon HTTP 429 responses.   # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from confidentify_client.configuration import Configuration


class MatchedPair(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'record1': 'MatchedRecord',
        'record2': 'MatchedRecord',
        'verdict': 'MatchVerdict',
        'scores': 'object'
    }

    attribute_map = {
        'record1': 'record1',
        'record2': 'record2',
        'verdict': 'verdict',
        'scores': 'scores'
    }

    def __init__(self, record1=None, record2=None, verdict=None, scores=None, local_vars_configuration=None):  # noqa: E501
        """MatchedPair - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._record1 = None
        self._record2 = None
        self._verdict = None
        self._scores = None
        self.discriminator = None

        if record1 is not None:
            self.record1 = record1
        if record2 is not None:
            self.record2 = record2
        if verdict is not None:
            self.verdict = verdict
        if scores is not None:
            self.scores = scores

    @property
    def record1(self):
        """Gets the record1 of this MatchedPair.  # noqa: E501


        :return: The record1 of this MatchedPair.  # noqa: E501
        :rtype: MatchedRecord
        """
        return self._record1

    @record1.setter
    def record1(self, record1):
        """Sets the record1 of this MatchedPair.


        :param record1: The record1 of this MatchedPair.  # noqa: E501
        :type: MatchedRecord
        """

        self._record1 = record1

    @property
    def record2(self):
        """Gets the record2 of this MatchedPair.  # noqa: E501


        :return: The record2 of this MatchedPair.  # noqa: E501
        :rtype: MatchedRecord
        """
        return self._record2

    @record2.setter
    def record2(self, record2):
        """Sets the record2 of this MatchedPair.


        :param record2: The record2 of this MatchedPair.  # noqa: E501
        :type: MatchedRecord
        """

        self._record2 = record2

    @property
    def verdict(self):
        """Gets the verdict of this MatchedPair.  # noqa: E501


        :return: The verdict of this MatchedPair.  # noqa: E501
        :rtype: MatchVerdict
        """
        return self._verdict

    @verdict.setter
    def verdict(self, verdict):
        """Sets the verdict of this MatchedPair.


        :param verdict: The verdict of this MatchedPair.  # noqa: E501
        :type: MatchVerdict
        """

        self._verdict = verdict

    @property
    def scores(self):
        """Gets the scores of this MatchedPair.  # noqa: E501

        Detailed score values for information  # noqa: E501

        :return: The scores of this MatchedPair.  # noqa: E501
        :rtype: object
        """
        return self._scores

    @scores.setter
    def scores(self, scores):
        """Sets the scores of this MatchedPair.

        Detailed score values for information  # noqa: E501

        :param scores: The scores of this MatchedPair.  # noqa: E501
        :type: object
        """

        self._scores = scores

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchedPair):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MatchedPair):
            return True

        return self.to_dict() != other.to_dict()
